package com.congxiaoyao.location.model;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GpsSampleRsp.proto

public final class GpsSampleRspOuterClass {
  private GpsSampleRspOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GpsSampleRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GpsSampleRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double lng = 1;</code>
     */
    double getLng();

    /**
     * <code>optional double lat = 2;</code>
     */
    double getLat();

    /**
     * <code>optional double vlng = 3;</code>
     */
    double getVlng();

    /**
     * <code>optional double vlat = 4;</code>
     */
    double getVlat();

    /**
     * <code>optional int64 carId = 5;</code>
     */
    long getCarId();

    /**
     * <code>optional int64 time = 6;</code>
     */
    long getTime();

    /**
     * <code>optional int64 queryId = 7;</code>
     */
    long getQueryId();
  }
  /**
   * Protobuf type {@code GpsSampleRsp}
   */
  public  static final class GpsSampleRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GpsSampleRsp)
      GpsSampleRspOrBuilder {
    // Use GpsSampleRsp.newBuilder() to construct.
    private GpsSampleRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GpsSampleRsp() {
      lng_ = 0D;
      lat_ = 0D;
      vlng_ = 0D;
      vlat_ = 0D;
      carId_ = 0L;
      time_ = 0L;
      queryId_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GpsSampleRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              lng_ = input.readDouble();
              break;
            }
            case 17: {

              lat_ = input.readDouble();
              break;
            }
            case 25: {

              vlng_ = input.readDouble();
              break;
            }
            case 33: {

              vlat_ = input.readDouble();
              break;
            }
            case 40: {

              carId_ = input.readInt64();
              break;
            }
            case 48: {

              time_ = input.readInt64();
              break;
            }
            case 56: {

              queryId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GpsSampleRspOuterClass.internal_static_GpsSampleRsp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GpsSampleRspOuterClass.internal_static_GpsSampleRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GpsSampleRsp.class, Builder.class);
    }

    public static final int LNG_FIELD_NUMBER = 1;
    private double lng_;
    /**
     * <code>optional double lng = 1;</code>
     */
    public double getLng() {
      return lng_;
    }

    public void setLng(double lng) {
      this.lng_ = lng;
    }

    public static final int LAT_FIELD_NUMBER = 2;
    private double lat_;
    /**
     * <code>optional double lat = 2;</code>
     */
    public double getLat() {
      return lat_;
    }

    public void setLat(double lat) {
      this.lat_ = lat;
    }

    public static final int VLNG_FIELD_NUMBER = 3;
    private double vlng_;
    /**
     * <code>optional double vlng = 3;</code>
     */
    public double getVlng() {
      return vlng_;
    }

    public static final int VLAT_FIELD_NUMBER = 4;
    private double vlat_;
    /**
     * <code>optional double vlat = 4;</code>
     */
    public double getVlat() {
      return vlat_;
    }

    public static final int CARID_FIELD_NUMBER = 5;
    private long carId_;
    /**
     * <code>optional int64 carId = 5;</code>
     */
    public long getCarId() {
      return carId_;
    }

    public static final int TIME_FIELD_NUMBER = 6;
    private long time_;
    /**
     * <code>optional int64 time = 6;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int QUERYID_FIELD_NUMBER = 7;
    private long queryId_;
    /**
     * <code>optional int64 queryId = 7;</code>
     */
    public long getQueryId() {
      return queryId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (lng_ != 0D) {
        output.writeDouble(1, lng_);
      }
      if (lat_ != 0D) {
        output.writeDouble(2, lat_);
      }
      if (vlng_ != 0D) {
        output.writeDouble(3, vlng_);
      }
      if (vlat_ != 0D) {
        output.writeDouble(4, vlat_);
      }
      if (carId_ != 0L) {
        output.writeInt64(5, carId_);
      }
      if (time_ != 0L) {
        output.writeInt64(6, time_);
      }
      if (queryId_ != 0L) {
        output.writeInt64(7, queryId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (lng_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, lng_);
      }
      if (lat_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lat_);
      }
      if (vlng_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, vlng_);
      }
      if (vlat_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, vlat_);
      }
      if (carId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, carId_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, time_);
      }
      if (queryId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, queryId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GpsSampleRsp)) {
        return super.equals(obj);
      }
      GpsSampleRsp other = (GpsSampleRsp) obj;

      boolean result = true;
      result = result && (
          Double.doubleToLongBits(getLng())
          == Double.doubleToLongBits(
              other.getLng()));
      result = result && (
          Double.doubleToLongBits(getLat())
          == Double.doubleToLongBits(
              other.getLat()));
      result = result && (
          Double.doubleToLongBits(getVlng())
          == Double.doubleToLongBits(
              other.getVlng()));
      result = result && (
          Double.doubleToLongBits(getVlat())
          == Double.doubleToLongBits(
              other.getVlat()));
      result = result && (getCarId()
          == other.getCarId());
      result = result && (getTime()
          == other.getTime());
      result = result && (getQueryId()
          == other.getQueryId());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + LNG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLng()));
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLat()));
      hash = (37 * hash) + VLNG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getVlng()));
      hash = (37 * hash) + VLAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getVlat()));
      hash = (37 * hash) + CARID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCarId());
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + QUERYID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getQueryId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GpsSampleRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GpsSampleRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GpsSampleRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GpsSampleRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GpsSampleRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GpsSampleRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GpsSampleRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GpsSampleRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GpsSampleRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GpsSampleRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GpsSampleRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GpsSampleRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GpsSampleRsp)
        GpsSampleRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GpsSampleRspOuterClass.internal_static_GpsSampleRsp_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GpsSampleRspOuterClass.internal_static_GpsSampleRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GpsSampleRsp.class, Builder.class);
      }

      // Construct using GpsSampleRspOuterClass.GpsSampleRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        lng_ = 0D;

        lat_ = 0D;

        vlng_ = 0D;

        vlat_ = 0D;

        carId_ = 0L;

        time_ = 0L;

        queryId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GpsSampleRspOuterClass.internal_static_GpsSampleRsp_descriptor;
      }

      public GpsSampleRsp getDefaultInstanceForType() {
        return GpsSampleRsp.getDefaultInstance();
      }

      public GpsSampleRsp build() {
        GpsSampleRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public GpsSampleRsp buildPartial() {
        GpsSampleRsp result = new GpsSampleRsp(this);
        result.lng_ = lng_;
        result.lat_ = lat_;
        result.vlng_ = vlng_;
        result.vlat_ = vlat_;
        result.carId_ = carId_;
        result.time_ = time_;
        result.queryId_ = queryId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GpsSampleRsp) {
          return mergeFrom((GpsSampleRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GpsSampleRsp other) {
        if (other == GpsSampleRsp.getDefaultInstance()) return this;
        if (other.getLng() != 0D) {
          setLng(other.getLng());
        }
        if (other.getLat() != 0D) {
          setLat(other.getLat());
        }
        if (other.getVlng() != 0D) {
          setVlng(other.getVlng());
        }
        if (other.getVlat() != 0D) {
          setVlat(other.getVlat());
        }
        if (other.getCarId() != 0L) {
          setCarId(other.getCarId());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getQueryId() != 0L) {
          setQueryId(other.getQueryId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GpsSampleRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GpsSampleRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double lng_ ;
      /**
       * <code>optional double lng = 1;</code>
       */
      public double getLng() {
        return lng_;
      }
      /**
       * <code>optional double lng = 1;</code>
       */
      public Builder setLng(double value) {
        
        lng_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double lng = 1;</code>
       */
      public Builder clearLng() {
        
        lng_ = 0D;
        onChanged();
        return this;
      }

      private double lat_ ;
      /**
       * <code>optional double lat = 2;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <code>optional double lat = 2;</code>
       */
      public Builder setLat(double value) {
        
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double lat = 2;</code>
       */
      public Builder clearLat() {
        
        lat_ = 0D;
        onChanged();
        return this;
      }

      private double vlng_ ;
      /**
       * <code>optional double vlng = 3;</code>
       */
      public double getVlng() {
        return vlng_;
      }
      /**
       * <code>optional double vlng = 3;</code>
       */
      public Builder setVlng(double value) {
        
        vlng_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double vlng = 3;</code>
       */
      public Builder clearVlng() {
        
        vlng_ = 0D;
        onChanged();
        return this;
      }

      private double vlat_ ;
      /**
       * <code>optional double vlat = 4;</code>
       */
      public double getVlat() {
        return vlat_;
      }
      /**
       * <code>optional double vlat = 4;</code>
       */
      public Builder setVlat(double value) {
        
        vlat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double vlat = 4;</code>
       */
      public Builder clearVlat() {
        
        vlat_ = 0D;
        onChanged();
        return this;
      }

      private long carId_ ;
      /**
       * <code>optional int64 carId = 5;</code>
       */
      public long getCarId() {
        return carId_;
      }
      /**
       * <code>optional int64 carId = 5;</code>
       */
      public Builder setCarId(long value) {
        
        carId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 carId = 5;</code>
       */
      public Builder clearCarId() {
        
        carId_ = 0L;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>optional int64 time = 6;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 6;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 6;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private long queryId_ ;
      /**
       * <code>optional int64 queryId = 7;</code>
       */
      public long getQueryId() {
        return queryId_;
      }
      /**
       * <code>optional int64 queryId = 7;</code>
       */
      public Builder setQueryId(long value) {
        
        queryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 queryId = 7;</code>
       */
      public Builder clearQueryId() {
        
        queryId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GpsSampleRsp)
    }

    // @@protoc_insertion_point(class_scope:GpsSampleRsp)
    private static final GpsSampleRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GpsSampleRsp();
    }

    public static GpsSampleRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GpsSampleRsp>
        PARSER = new com.google.protobuf.AbstractParser<GpsSampleRsp>() {
      public GpsSampleRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GpsSampleRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GpsSampleRsp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GpsSampleRsp> getParserForType() {
      return PARSER;
    }

    public GpsSampleRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GpsSampleRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GpsSampleRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022GpsSampleRsp.proto\"r\n\014GpsSampleRsp\022\013\n\003" +
      "lng\030\001 \001(\001\022\013\n\003lat\030\002 \001(\001\022\014\n\004vlng\030\003 \001(\001\022\014\n\004" +
      "vlat\030\004 \001(\001\022\r\n\005carId\030\005 \001(\003\022\014\n\004time\030\006 \001(\003\022" +
      "\017\n\007queryId\030\007 \001(\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GpsSampleRsp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GpsSampleRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GpsSampleRsp_descriptor,
        new String[] { "Lng", "Lat", "Vlng", "Vlat", "CarId", "Time", "QueryId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
